# Numpy: Views and Copies
We need to be careful when we are dealing with Numpy.  Sometimes two variables can point to the same array data.  This means that changing one will affect the other.

In [3]:
import numpy as np


## Assignment points to the same array

If we assign a to b, they just point to the same data.  Look at the ids of the objects below.  a and b are identical:

In [4]:
a = np.arange(10)
b = a
print("a: {} b: {}".format(id(a),id(b)))

a: 1599382623696 b: 1599382623696


## Views point to the same array

If we make a view, c, on a using view(), a and c share the same data, but are different objects:  

In [5]:
a = np.arange(10)
c = a.view()
print("a: {} c: {}".format(id(a),id(c)))

a: 1599487754928 c: 1599487754768


If we change the value of a cell in a then c's value also changes:

In [6]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a[0] = 10
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [8]:
c

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

## A deep copy is needed to make a completely new copy

If we take a copy of a using copy(), the copy has it's own copy of the data.  If we change a then d does not change:

In [9]:
a = np.arange(10)
d = a.copy()

In [10]:
a[0] = 11
a

array([11,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [11]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## A slice is a view on the same data


If we take a slice of a and change a the slice also changes:

In [12]:
a = np.arange(10)
e = a[0:4]
a[0] = 12
a

array([12,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [13]:
e

array([12,  1,  2,  3])