# Numpy: Arithmetic Operations

In [1]:
import numpy as np

## Operations on 2 arrays

We can take two arrays and perform arithmetic operations on them.  The operation is applied to every element in one operation:

In [4]:
a = np.array( [20,30,40,50] )
b = np.array( [0, 1, 2, 3] )

# Elementwise subtract
c = a - b
c


array([20, 29, 38, 47])

In [5]:
# Elementwise exp
d = b**2
d

array([0, 1, 4, 9], dtype=int32)

In [6]:
# Elementwise sin
e = 10*np.sin(a)
e

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [7]:
# Elementwise comparison
f = a<35
f

array([ True,  True, False, False])

In [8]:
# Elementwise multiplication
g = a * b
g

array([  0,  30,  80, 150])

## Dot product

In [23]:
aa = np.array( [[1,1],
                [2,4] ,
                [3,3]] )
bb = np.array( [[2],
                [3]] )

In [24]:
h = aa.dot(bb)
h

array([[ 5],
       [16],
       [15]])

If you need a refresher on what dot product means, watch his video:

https://youtu.be/BcxfxvYCL1g

and watch this one to understand how you might use a dot product:

https://youtu.be/TBpDMLCC2uY
