# Introduction to Numpy

In Python, you have lists.  You can put any data type into lists and have multi-dimensional lists.  But Python lists are not optimised for fast processing of large data sets.  For this, we turn to Numpy.

Numpy is written in C, but has a Python wrapper.  This gives the best of both worlds - the speed of compiler C code and the ease of use that Python gives us.

## What do you get with Numpy?

- Fast multi-dimensional arrays of data
- A wealth of mathematical and data manipulation functions that operate on the entire data array at once (so you don't have to loop through each element)


## How do I use Numpy?
You can use Numpy in it's raw form, but most often you will use it through one of the numerous libraries that have been written on top of Numpy.  E.g.

- Pandas, for data table operations
- OpenCV, for image processing
- Scikit-Learn, for machine learning

And many, many more.

See https://numpy.org/ for more details.


## Recommendations for learning Numpy
Most of what you need to do with Numpy you will do through higher-level libraries such as Pandas.  I'd recommend you start with those, and dive into Numpy if and when you need to do something at that more fine-grained level.

# Numpy: Basic Operations

In this notebook we will learn some basic numpy operations so you get a flavour of what's possible.  We'll delve deeper later.

## Importing numpy
The standard way to import numpy uses the alias **np**:

In [1]:
import numpy as np

## Creating a numpy array from literal data

Create a numpy array from data:

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Reshaping data

We can reshape the above one-dimensional array into a 2D one:

In [3]:
a = a.reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Add now into a 3D one:

In [4]:
a = a.reshape(3,2,2)
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

We can interrogate the shape:

In [5]:
a.shape

(3, 2, 2)

We can find out the number of dimensions:

In [6]:
a.ndim

3

We can find out the data type:

In [7]:
a.dtype

dtype('int32')