## Arrays and NumPy Arrays

This lab will constitute practice with Python lists and NumPy arrays. If you've been struggling with Python data structures, this will be a good chance to refine your understanding. None of the tasks here will take more than a couple of lines of code (Python or NumPy tasks), so keep that in mind if you find yourself writing a lot of Python to solve a problem. Lots of code to do something simple is bad practice!

If you get stuck there are plenty of references [here](https://docs.python.org/3/tutorial/datastructures.html) and [here](https://numpy.org/doc/stable/)

Be sure to test your code with different values for the example data -- exploration is key to learning.

### Try not to use StackOverflow.
If you get stuck, jump into the discussion forums and explain your logic and where you are stuck. Equally, if you 
find this easy you might want to jump in and help others. A good way to learn is explaining topics and concepts.



In [1]:
# Need to import numpy for this
import numpy as np

In [2]:
## Sample tasks with data and solutions.
P = [1,2,3,6,3,1,4,7,9,4,5,9]
N = np.array(P)

## Task 0a: print the maximum value of Python list P without using NumPy:
print(max(P)) # max() is a Python function that operates on lists

## Task 0b: print the maximum value of NumPy array N using NumPy functions:
print(N.max()) # N.max() is a function of NumPy Arrays. Note the syntax and that it doesn't take any arguments

9
9


In [3]:
## Note that Python prints Python lists slightly differently than NumPy Arrays
## Don't worry about this...

print([1,2,3])
print(np.array([1,2,3]))

[1, 2, 3]
[1 2 3]


## The Lab

From this cell onward, you need to complete the tasks specified in each cell. Please keep your solutions to a single cell -- you do not need define new functions. If you create extra cells to test things, you can always delete them afterwards.

In [9]:
P = [1,2,3,6,3,1,4,7,9,4,5,9]
N = np.array(P)
## Task 1a: Print the average (arithmetic mean) of Python list P without using NumPy:
print(sum(P)/len(P)) # sum() is a Python function that operates on lists

## Task 1b: Print the average (arithmetic mean) of NumPy array N without using NumPy:
print(np.mean(N)) # np.mean() is a function of NumPy Arrays. Note the syntax and that it doesn't take any argumentss


4.5
4.5


In [10]:
P1 = [1,2,3,6,3,1,4,7,9,4,5,9]
N1 = np.array(P1)

P2 = [-1,-2,-3,-6,-3,-1,-4,-7,-9,-4,-5,-9]
N2 = np.array(P2)
## Task 2a: Concatonate and print Python list P1 with P2 without using NumPy:
print(P1+P2) # + is a Python operator that operates on lists

## Task 2a: Concatonate and print NumPy array N1 with N2 using NumPy:
print(np.concatenate((N1,N2))) # np.concatenate() is a function of NumPy Arrays. Note the syntax and that it takes an argument


[1, 2, 3, 6, 3, 1, 4, 7, 9, 4, 5, 9, -1, -2, -3, -6, -3, -1, -4, -7, -9, -4, -5, -9]
[ 1  2  3  6  3  1  4  7  9  4  5  9 -1 -2 -3 -6 -3 -1 -4 -7 -9 -4 -5 -9]


In [12]:
P1 = [1,2,3,6,3,1,4,7,9,4,5,9]
N1 = np.array(P1)

P2 = [-1,-2,-3,-6,-3,-1,-4,-7,-9,-4,-5,-9]
N2 = np.array(P2)

## Task 3a: Add every value of Python list P1 to the corresponding value in P2 and print the result:
print([P1[i]+P2[i] for i in range(len(P1))]) # This is a list comprehension. It's a way of writing a for loop in one line

# Bonus task: can you do it without overwriting P1 or P2? Without a loop and an intermediate variable?


## Task 3a: Add every value of NumPy array N1 to the corresponding value in N2 and print the result:
print(N1+N2) # + is a NumPy operator that operates on NumPy Arrays. Note the syntax and that it doesn't take any arguments

# Open question: What should this task do if the lengths of the arrays are not equal? Why?
# Hint: What happens if you try to add two arrays of different lengths?

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0 0 0 0 0 0 0 0 0 0 0 0]


In [14]:
P = [1,2,3,6,3,1,4,7,9,4,5,9]
N = np.array(P)

## Task 4a: Print the result of swapping the first and second halves of Python list P.
## If the length of P is odd, the middle element should not be moved
## Example: [1,2,3,4] -> [3,4,1,2]; [1,2,3,4,5] -> [4,5,3,1,2]
print(P[len(P)//2:]+P[:len(P)//2]) # This is a list slice. It's a way of accessing a subset of a list

## Task 4a: Swap the first and second halves of NumPy array N. If the length of P is even, the middle 
## If the length of N is odd, the middle element should not be moved
print(np.concatenate((N[len(N)//2:],N[:len(N)//2]))) # np.concatenate() is a function of NumPy Arrays. Note the syntax and that it takes an argument

## Note that NumPy doesn't simplify everything! :)

[4, 7, 9, 4, 5, 9, 1, 2, 3, 6, 3, 1]
[4 7 9 4 5 9 1 2 3 6 3 1]


In [16]:
# If you're not sure of the definition of Standard Deviation, do some googlin'
P = [1,2,3,6,3,1,4,7,9,4,5,9]
N = np.array(P)

## Task 5a: Compute and print the stadard deviation of Python list P without using NumPy:
# Note that you may need new variables to hold intermediate values
# Hint: remember that the square root of x is equivalent x to the power of .5
print((sum([(i-sum(P)/len(P))**2 for i in P])/len(P))**.5) # This is a list comprehension. It's a way of writing a for loop in one line


## Task 5b: Compute and print the standard deviation of NumPy array N using NumPy:
print(np.std(N)) # np.std() is a function of NumPy Arrays. Note the syntax and that it doesn't take any arguments


2.661453237111885
2.661453237111885
