# Numpy: Reshaping
Reshaping is about changing the dimensionality of the data.

In [2]:
import numpy as np

Here we have a 2d array, organised as a 5x4 matrix:

In [10]:
b = np.array([[ 0,  1,  2,  3, 4],
              [10, 11, 12, 13, 14],
              [20, 21, 22, 23, 24],
              [30, 31, 32, 33, 34]])

We can flatten this into one dimension:

In [11]:
# Flatten
b.ravel()

array([ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34])

We can redimension the above 5x5 matrix into a 2x10 matrix:

In [12]:
# Reshape
b.reshape(2,10)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24, 30, 31, 32, 33, 34]])

We can swap the rows and columns:

In [13]:
# Transpose
b.T

array([[ 0, 10, 20, 30],
       [ 1, 11, 21, 31],
       [ 2, 12, 22, 32],
       [ 3, 13, 23, 33],
       [ 4, 14, 24, 34]])