# Numpy: Indexing and Slicing


In [1]:
import numpy as np

## One dimensional arrays

First let's define a one and two-dimensional array:

In [2]:
a = np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10])

We can reference a cell in the array:

In [43]:
a[5]

5

We can cut a slice from the array:

In [3]:
a[3:6]

array([3, 4, 5])

Slice an array starting at index 2, ending at index 10, with steps of 3:

In [4]:
a[slice(2,10,3)]

array([2, 5, 8])

In [5]:
a[2:10:3]

array([2, 5, 8])

## Two dimensional arrays

First let's define a two dimensional array:

In [6]:
b = np.array([[ 0,  1,  2,  3, 4],
              [10, 11, 12, 13, 14],
              [20, 21, 22, 23, 24],
              [30, 31, 32, 33, 34],
              [40, 41, 42, 43, 44]])

We can reference a cell in the array:

In [7]:
b[2,3]

23

Get a row from the 2D array:

In [8]:
b[3,:]

array([30, 31, 32, 33, 34])

Get column from the 2D array:

In [9]:
b[:,2]

array([ 2, 12, 22, 32, 42])

Get multiple rows from the 2D array:

In [10]:
b[1:4, : ]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

Get a 2D slice from the 2D array:

In [11]:
b[2:4,3:5]

array([[23, 24],
       [33, 34]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [42]:
b[1]

array([10, 11, 12, 13, 14])

## Iterating over arrays

Iterate over the multi-dimensional array rows:

In [12]:
for row in b:
    print(row)

[0 1 2 3 4]
[10 11 12 13 14]
[20 21 22 23 24]
[30 31 32 33 34]
[40 41 42 43 44]


Iterate over the multi-dimensional array elements by flattening the array:

In [13]:
for element in b.flat:
    print(element)

0
1
2
3
4
10
11
12
13
14
20
21
22
23
24
30
31
32
33
34
40
41
42
43
44


## Integer indexing

We can use lists of row and column indices to slice:

In [14]:
rows = [0,2,4]
cols = [0,3,3]
b[rows, cols] 

array([ 0, 23, 43])

## Boolean indexing

We can apply a condition to pull out elements:

In [15]:
b[b>20]

array([21, 22, 23, 24, 30, 31, 32, 33, 34, 40, 41, 42, 43, 44])

In [5]:
b[b!=0]

array([ 1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31, 32,
       33, 34, 40, 41, 42, 43, 44])