# Numpy: Basic Operations

In this notebook we will learn some basic numpy operations so you get a flavour of what's possible.  We'll delve deeper later.

## Importing numpy
The standard way to import numpy uses the alias **np**:

In [1]:
import numpy as np

## Creating a numpy array from literal data

Create a numpy array from data:

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Reshaping data

We can reshape the above one-dimensional array into a 2D one:

In [3]:
a = a.reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Add now into a 3D one:

In [4]:
a = a.reshape(3,2,2)
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

We can interrogate the shape:

In [5]:
a.shape

(3, 2, 2)

We can find out the number of dimensions:

In [6]:
a.ndim

3

We can find out the data type:

In [7]:
a.dtype

dtype('int32')

We can find out the total number of elements in the array:

In [8]:
a.size

12

We can find out the size of an element in the array.  Note that all elements are the same size:

In [9]:
a.itemsize

4