## Arrays and NumPy Arrays

This lab will constitute practice with Python lists and NumPy arrays. If you've been struggling with Python data structures, this will be a good chance to refine your understanding. None of the tasks here will take more than a couple of lines of code (Python or NumPy tasks), so keep that in mind if you find yourself writing a lot of Python to solve a problem. Lots of code to do something simple is bad practice!

The accompanying `numpy_arrays_practice` notebook has some examples of NumPy Arrays and related operations. You will probably need to refer to [Python List](https://docs.python.org/3/tutorial/datastructures.html) and [NumPy Array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) documentation online. 

Do your best. We have provided solutions for you but try to have a go before looking at the answers.

In [1]:
# Need to import numpy for this lab
import numpy as np

In [2]:
## Sample tasks with data and solutions.
P = [1,2,3,6,3,1,4,7,9,4,5,9]
N = np.array(P)

## Task 0a: print the maximum value of Python list P without using NumPy:
print(max(P)) # max() is a Python function that operates on lists

## Task 0b: print the maximum value of NumPy array N using NumPy functions:
print(N.max()) # N.max() is a function of NumPy Arrays. Note the syntax and that it doesn't take any arguments
# Output should be the same. Check below...

9
9


In [3]:
## Note that Python prints Python lists slightly differently than NumPy Arrays
## Don't worry about this...

print([1,2,3])
print(np.array([1,2,3]))

[1, 2, 3]
[1 2 3]


## Let's code!

From this cell onward, you need to complete the tasks specified in each cell. Please keep your solutions to a single cell -- you do not need define new functions.

In [4]:
P = [1,2,3,6,3,1,4,7,9,4,5,9]
N = np.array(P)
## Task 1a: Print the average (arithmetic mean) of Python list P without using NumPy:
print(sum(P)/len(P))


## Task 1b: Print the average (arithmetic mean) of NumPy array N without using NumPy:
print(N.mean()) # N.mean() is a function of NumPy Arrays. Note the syntax and that it doesn't take any arguments


4.5
4.5


<details>
  <summary>Click to see answers</summary>
    #1a<br/>
    print(sum(P)/len(P))<br/>
    #1b<br/>
    print(sum(N)/len(N))<br/>
</details>

In [5]:
P1 = [1,2,3,6,3,1,4,7,9,4,5,9]
N1 = np.array(P1)

P2 = [-1,-2,-3,-6,-3,-1,-4,-7,-9,-4,-5,-9]
N2 = np.array(P2)
## Task 2a: Concatenate and print Python list P1 with P2 without using NumPy:
print(P1+P2)


## Task 2b: Concatenate and print NumPy array N1 with N2 using NumPy:
print(np.concatenate((N1,N2))) # np.concatenate() is a function of NumPy Arrays. Note the syntax and that it takes two arguments


[1, 2, 3, 6, 3, 1, 4, 7, 9, 4, 5, 9, -1, -2, -3, -6, -3, -1, -4, -7, -9, -4, -5, -9]
[ 1  2  3  6  3  1  4  7  9  4  5  9 -1 -2 -3 -6 -3 -1 -4 -7 -9 -4 -5 -9]


<details>
  <summary>Click to see answers</summary>
    Task 2a print(P1 + P2)<br/>
    Task 2b print(np.concatenate([N1, N2]))<br/>
</details>

In [8]:
P1 = [1,2,3,6,3,1,4,7,9,4,5,9]
N1 = np.array(P1)

P2 = [-1,-2,-3,-6,-3,-1,-4,-7,-9,-4,-5,-9]
N2 = np.array(P2)

## Task 3a: Add every value of Python list P1 to the corresponding value in P2 and print the result.
# Hint, your output should be 0
print([P1[i]+P2[i] for i in range(len(P1))])

# Bonus task: can you do it without overwriting P1 or P2? Without a loop and an intermediate variable?

## Task 3b: Add every value of NumPy array N1 to the corresponding value in N2 and print the result:
print(N1+N2) # N1+N2 is a function of NumPy Arrays. Note the syntax and that it doesn't take any arguments

# Open question: What should this task do if the lengths of the arrays are not equal? Why?



[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0 0 0 0 0 0 0 0 0 0 0 0]


<details>
  <summary>Click to see answers</summary>
3a) <br />
    print([P1[idx] + P2[idx] for idx in range(len(P1))]) <br />

Bonus task) <br />
    Another way could be: print(list(map(sum, zip(P1, P2)))) <br />

3b) <br />
    print(N1 + N2) <br />

#Open question answer:
Be careful with unequal arrays. We do not necessarily know the mapping between objects if they are not equal. We   do not want our code making decisions about logic without first understanding the underlying data structure!

</details>

In [10]:
P = [1,2,3,6,3,1,4,7,9,4,5,9]
N = np.array(P)

## Task 4a: Print the result of swapping the first and second halves of Python list P.
## If the length of P is odd, the middle element should not be moved
## Example: [1,2,3,4] -> [3,4,1,2]; [1,2,3,4,5] -> [3,4,5,1,2]
print(P[len(P)//2:]+P[:len(P)//2])


## Task 4b: Swap the first and second halves of NumPy array N. If the length of P is even, the middle 
## If the length of N is odd, the middle element should not be moved
print(np.concatenate((N[len(N)//2:],N[:len(N)//2]))) # np.concatenate() is a function of NumPy Arrays. Note the syntax and that it takes two arguments

## Note that NumPy doesn't simplify everything! :)

[4, 7, 9, 4, 5, 9, 1, 2, 3, 6, 3, 1]
[4 7 9 4 5 9 1 2 3 6 3 1]


<details>
  <summary>Click to see answers</summary>
4a) <br /> half_size = round(len(P) / 2) <br />
print(P[-half_size:] + P[half_size:-half_size] + P[:half_size])<br />
4b) <br /> print(np.concatenate([N[-half_size:], N[half_size:-half_size], N[:half_size]]))<br />
    
</details>

In [13]:
# If you're not sure of the definition of Standard Deviation, do some googlin'
P = [1,2,3,6,3,1,4,7,9,4,5,9]
N = np.array(P)

## Task 5a: Compute and print the standard deviation of Python list P without using NumPy:
# Note that you may need new variables to hold intermediate values
# Hint: remember that the square root of x is equivalent x to the power of .5
print((sum([(i-sum(P)/len(P))**2 for i in P])/len(P))**.5)


# Using Python standard library "statistics"
import statistics
print(statistics.stdev(P))


## Task 5b: Compute and print the standard deviation of NumPy array N using NumPy:
print(np.std(N)) # np.std() is a function of NumPy Arrays. Note the syntax and that it doesn't take any arguments


2.661453237111885
2.7797972457128464
2.661453237111885


<details>
  <summary>Click to see answers</summary>
5a) <br /> import math<br />
mean_P = sum(P) / len(P)
print(math.sqrt(sum([math.pow(num - mean_P, 2) for num in P]) / (len(P)-1)))<br />
Using Python standard library "statistics"<br />
import statistics<br />
print(statistics.stdev(P))<br />

5b) <br /> print(np.std(N, ddof=1))
</details>